
// src/app/layout.tsx
import React from 'react';
import { UserProvider } from './UserContext'; // Adjust the path as necessary
import Navbar from './components/Navbar';
import Footer from './components/footer';
export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
        <Navbar />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
